In [68]:
import numpy as np

v1 = np.array([1,2,3])
v2 = np.array([6,7,8])

norm1 = np.linalg.norm(v1)
norm2 = np.linalg.norm(v2)

cross = np.cross(v1, v2)

dot = np.dot(v1, v2)

min1 = v1.min()
min2 = v2.min()

max1 = v1.max()
max2 = v2.max()

mean1 = v1.mean()
mean2 = v2.mean()

var1 = v1.var()
var2 = v2.var()

std1 = v1.std()
std2 = v2.std()

print(f"Норма1: {norm1 :<.3f}                Норма2: {norm2 :<.3f}")
print(f"cross: {cross}            dot: {dot}")
print(f"min1: {min1}                      min2: {min2}")
print(f"max1: {max1}                      max2: {max2}")
print(f"mean1: {mean1}                   mean2: {mean2}")
print(f"var1: {var1 :<.3f}                  var2: {var2 :<.3f}")
print(f"std1: {std1 :<.3f}                  std2: {std2 :<.3f}")

Норма1: 3.742                Норма2: 12.207
cross: [-5 10 -5]            dot: 44
min1: 1                      min2: 6
max1: 3                      max2: 8
mean1: 2.0                   mean2: 7.0
var1: 0.667                  var2: 0.667
std1: 0.816                  std2: 0.816


# **#2** Определить и вывести на экран три прямоугольные матрицы, заполнив одну из них случайными числами, а две другие — используя функцию *fromfunction*(), выбрав два закона:

In [81]:
mtrx1 = np.random.normal(size=(2,3))
mtrx2 = np.fromfunction(lambda i, j: i*i, shape=(7,10))
mtrx3 = np.fromfunction(lambda i, j: i+i-5, shape=(7,10))

# **#3** Найти и вывести на экран для каждой матрицы: след матрицы и транспонированную матрицу, проверить свойство диагонального преобладания

In [106]:
print(mtrx1.T, end='\n\n')
print(mtrx2.T, end='\n\n')
print(mtrx3.T, end='\n\n')

print(mtrx1.trace())
print(mtrx2.trace())
print(mtrx3.trace(), end='\n\n')

print(abs(mtrx1).sum(axis=1) < abs(mtrx1.diagonal()))
print(abs(mtrx2).sum(axis=1) < abs(mtrx2.diagonal()))
print(abs(mtrx3).sum(axis=1) < abs(mtrx3.diagonal()))

[[ 0.31248584 -0.1973165 ]
 [ 0.27946438  0.29367914]
 [ 1.19091909 -1.90702508]]

[[ 0.  1.  4.  9. 16. 25. 36.]
 [ 0.  1.  4.  9. 16. 25. 36.]
 [ 0.  1.  4.  9. 16. 25. 36.]
 [ 0.  1.  4.  9. 16. 25. 36.]
 [ 0.  1.  4.  9. 16. 25. 36.]
 [ 0.  1.  4.  9. 16. 25. 36.]
 [ 0.  1.  4.  9. 16. 25. 36.]
 [ 0.  1.  4.  9. 16. 25. 36.]
 [ 0.  1.  4.  9. 16. 25. 36.]
 [ 0.  1.  4.  9. 16. 25. 36.]]

[[-5. -3. -1.  1.  3.  5.  7.]
 [-5. -3. -1.  1.  3.  5.  7.]
 [-5. -3. -1.  1.  3.  5.  7.]
 [-5. -3. -1.  1.  3.  5.  7.]
 [-5. -3. -1.  1.  3.  5.  7.]
 [-5. -3. -1.  1.  3.  5.  7.]
 [-5. -3. -1.  1.  3.  5.  7.]
 [-5. -3. -1.  1.  3.  5.  7.]
 [-5. -3. -1.  1.  3.  5.  7.]
 [-5. -3. -1.  1.  3.  5.  7.]]

0.6061649724515998
91.0
7.0

[False False]
[False False False False False False False]
[False False False False False False False]
